#!/usr/bin/env bash
mkdir -p projects/WEBART/repos && \
cd projects/WEBART/repos && \
g clone ssh://git@git.hq.local:7999/webart/adviser-advanced-search_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/adviser-simple-search_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/app1_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/app2_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-deploy-integration-test_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-form-nominations_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-account_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-adviser-account_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-adviser-applicant-details_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-adviser-beneficiaries_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-adviser-idps-applicant-details_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-adviser-idps-new-business_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-adviser-idps-next-steps_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-adviser-new-business_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-adviser-profile_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-adviser-registration_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-adviser-reporting_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-auto-reweights_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-banner-ads_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ca-dashboard_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-client-corporate-actions_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-client-profile_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-deposits-and-transfers_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-display-message_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-family-fee-aggregation_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-fees_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-income-distribution_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-income-stream-reporting_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-inspecie_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-insurance_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-investment-picker_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-investments_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-link-accounts_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-login_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-member-account_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-member-advice-fee-ongoing_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-member-reporting_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-member-summary_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-member-supermatch_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-mysuper-opt-out_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-new-business-application_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-account_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-account-details_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-advice-fees_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-aiir_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-akf_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-client_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-employer_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-fees_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-idps-new-business_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-insurance_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-insurance-optin_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-insurance-premium-nominated_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-letters_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-maturity-investment_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-mda-linked-accounts_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-mps-linked-accounts_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-qtfn_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-release-condition_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-search_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-statements_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-order-confirmation_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-order-monitor_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-password-reset_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-pension_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-profile-settings_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-recent-forms_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-registration_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-reweights_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-rollovers_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-standing-instructions_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-summary-carousel_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-transactions_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-withdrawal_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/balance-graph_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/gel-colours_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/market-exposure-graph_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/package-of-packages_artifactPUBLIC.git && \
g clone ssh://git@git.hq.local:7999/webart/react-pdf-beneficiary_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/react-pdf-direct-debit_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/react-pdf-new-business-application_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/react-pdf-roa-tef_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/react-pdf-withdrawal-receipt_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/react-redux-component-boilerplate_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/report-archive_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/report-request_artifact && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-advice-fees_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-account-details_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-aiir_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-client_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-akf_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-employer_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-idps-new-business_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-fees_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-insurance_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-insurance-premium-nominated_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-insurance-optin_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-letters_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-mda-linked-accounts_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-maturity-investment_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-mps-linked-accounts_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-release-condition_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-qtfn_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-search_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-order-confirmation_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-ops-statements_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-order-monitor_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-pension_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-password-reset_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-profile-settings_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-registration_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-recent-forms_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-reweights_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-standing-instructions_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-rollovers_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-summary-carousel_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-withdrawal_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/asis-web-transactions_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/balance-graph_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/market-exposure-graph_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/gel-colours_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/package-of-packages_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/react-pdf-direct-debit_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/react-pdf-beneficiary_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/react-pdf-new-business-application_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/react-pdf-withdrawal-receipt_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/react-pdf-roa-tef_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/react-redux-component-boilerplate_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/report-archive_artifact.git && \
g clone ssh://git@git.hq.local:7999/webart/report-request_artifact.git
